### ISSUE TITLE
Feature: Validate OAuth scopes

### ISSUE THREAD

**Issue by david0** [mservicetech/openapi-schema-validation#52]
in our schemas we use scopes:
```yaml
paths:
  /users/:
      security:
        - OAuth2: [read_users]     # <------
 ```

It would be great if this library could also verify this part of the spec if the current users scopes are handed over.

If thats too much, maybe an API could be provided to get the matched current Path object from the schema to add additional validation?
